version: '3.8'
services:
  api:
    build: api
    volumes:
      - ../code:/var/www/html/acme/bankholiday
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../code:/var/www/html/acme/bankholiday
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - api
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acme
      - MYSQL_USER=bankholiday_user
      - MYSQL_PASSWORD=1234