doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
        charset: utf8mb4

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Api:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/BankHoliday/Api/Infrastructure/Database/BankHoliday/Doctrine/Mapping'
                prefix: 'Acme\Services\BankHoliday\Api\Infrastructure\Database\BankHoliday\Doctrine\Entity'
                alias: App
        dql:
            string_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year
